-- ORDERS TABLE
CREATE TABLE ORDERS (P_ID INT, P_NAME VARCHAR(50),PRICE_$ INT, P_TYPE VARCHAR(25));

-- Creating Trigger
CREATE OR REPLACE TRIGGER T1
AFTER INSERT ON ORDERS
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Record inserted successfully');
END;

-- Testing Trigger
INSERT INTO ORDERS VALUES ('1', 'Core i5 13600K','408', 'CPU');
INSERT INTO ORDERS VALUES ('2', 'Core i7 13790F','499', 'CPU');
INSERT INTO ORDERS VALUES ('3', 'Core i9 13900KF','719', 'CPU');
INSERT INTO ORDERS VALUES ('4', 'MSI Pro Z790-A','505', 'Motherboard');
INSERT INTO ORDERS VALUES ('5', 'ASUS ROG Maximus Z790 HERO','798', 'Motherboard');