CREATE TABLE  AGENTS
(
    AGENT_CODE INT, AGENT_NAME VARCHAR(40),
    WORKING_AREA VARCHAR(35), COMMISSION INT
);
INSERT INTO AGENTS VALUES ('1', 'Subbarao', 'Bangalore', '14');
INSERT INTO AGENTS VALUES ('2', 'Mukesh', 'Mumbai', '11');
INSERT INTO AGENTS VALUES ('3', 'Alex ', 'London', '13');
INSERT INTO AGENTS VALUES ('4', 'Ivan', 'Torento', '15');
INSERT INTO AGENTS VALUES ('5', 'Anderson', 'Brisban', '13');
INSERT INTO AGENTS VALUES ('6', 'McDen', 'London', '15');
INSERT INTO AGENTS VALUES ('7', 'Ramasundar', 'Bangalore', '15');
INSERT INTO AGENTS VALUES ('8', 'Alford', 'New York', '12');
INSERT INTO AGENTS VALUES ('9', 'Benjamin', 'Hampshair', '11');
INSERT INTO AGENTS VALUES ('10', 'Santakumar', 'Chennai', '14');
INSERT INTO AGENTS VALUES ('11', 'Ravi Kumar', 'Bangalore', '15');
INSERT INTO AGENTS VALUES ('12', 'Lucida', 'San Jose', '12');

-- LIKE
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE 'R%';
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE '%d';
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE '%or%';
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE '_uk%';
SELECT * FROM AGENTS WHERE AGENT_NAME LIKE 'A%n';

-- NOT LIKE
SELECT * FROM AGENTS WHERE AGENT_NAME NOT LIKE 'A%';

-- BETWEEN
SELECT * FROM AGENTS WHERE COMMISSION BETWEEN 13 AND 14;

-- NOT BETWEEN
SELECT * FROM AGENTS WHERE COMMISSION NOT BETWEEN 12 AND 15;

-- IN
SELECT * FROM AGENTS WHERE WORKING_AREA IN ('New York', 'Brisban');

-- NOT IN
SELECT * FROM AGENTS WHERE WORKING_AREA NOT IN ('New York', 'Brisban', 'Mumbai', 'Torento', 'Chennai', 'Hampshair','San Jose','Bangalore');