-- Products Table
CREATE TABLE PRODUCTS (P_ID INT, P_NAME VARCHAR(50), P_TYPE VARCHAR(25));
INSERT INTO PRODUCTS VALUES ('1', 'Core i5 13600T', 'CPU');
INSERT INTO PRODUCTS VALUES ('2', 'Core i7 13790F', 'CPU');
INSERT INTO PRODUCTS VALUES ('3', 'Core i9 13900KF', 'CPU');
INSERT INTO PRODUCTS VALUES ('4', 'MSI Pro Z790-A', 'Motherboard');
INSERT INTO PRODUCTS VALUES ('5', 'ASUS ROG Maximus Z790 HERO', 'Motherboard');
INSERT INTO PRODUCTS VALUES ('6', 'Gigabyte Z690 Aero D', 'Motherboard');
INSERT INTO PRODUCTS VALUES ('7', 'Nvidia RTX 3090', 'GPU');
INSERT INTO PRODUCTS VALUES ('8', 'Nvidia RTX 4080', 'GPU');
INSERT INTO PRODUCTS VALUES ('9', 'Nvidia RTX 4090', 'GPU');
INSERT INTO PRODUCTS VALUES ('10', 'GSkill Trident Z5', 'Memory');
INSERT INTO PRODUCTS VALUES ('11', 'Corsair Vengeance', 'Memory');
INSERT INTO PRODUCTS VALUES ('12', 'Samsung 990 Pro', 'Storage');
INSERT INTO PRODUCTS VALUES ('13', 'WD Black SN850X', 'Storage');
INSERT INTO PRODUCTS VALUES ('14', 'MSI MAG Series CORELIQUID 360R V2', 'Cooler');
INSERT INTO PRODUCTS VALUES ('15', 'ARCTIC Liquid Freezer II 360 A-RGB', 'Cooler');
SELECT * FROM PRODUCTS;

-- Inventory Table
CREATE Table INVENTORY (P_ID INT, P_NAME VARCHAR(50), QUANTITY INT);
INSERT INTO INVENTORY VALUES ('2', 'Core i7 13790F', '14');
INSERT INTO INVENTORY VALUES ('3', 'Core i9 13900KF', '2');
INSERT INTO INVENTORY VALUES ('4', 'MSI Pro Z790-A', '7');
INSERT INTO INVENTORY VALUES ('6', 'Gigabyte Z690 Aero D', '5');
INSERT INTO INVENTORY VALUES ('8', 'Nvidia RTX 4080', '50');
INSERT INTO INVENTORY VALUES ('9', 'Nvidia RTX 4090', '99');
INSERT INTO INVENTORY VALUES ('10', 'GSkill Trident Z5', '64');
INSERT INTO INVENTORY VALUES ('12', 'Samsung 990 Pro', '40');
INSERT INTO INVENTORY VALUES ('13', 'WD Black SN850X', '6');
INSERT INTO INVENTORY VALUES ('14', 'MSI MAG Series CORELIQUID 360R V2', '10');
SELECT * FROM INVENTORY;

-- JOINS
-- INNER JOIN
SELECT PRODUCTS.P_ID, PRODUCTS.P_NAME, INVENTORY.QUANTITY, PRODUCTS.P_TYPE
FROM PRODUCTS
INNER JOIN INVENTORY ON PRODUCTS.P_ID = INVENTORY.P_ID;

-- LEFT JOIN
SELECT PRODUCTS.P_ID, PRODUCTS.P_NAME, INVENTORY.QUANTITY, PRODUCTS.P_TYPE
FROM PRODUCTS
LEFT JOIN INVENTORY ON PRODUCTS.P_ID = INVENTORY.P_ID;

-- RIGHT JOIN
SELECT PRODUCTS.P_ID, PRODUCTS.P_NAME, INVENTORY.QUANTITY, PRODUCTS.P_TYPE
FROM INVENTORY
RIGHT JOIN PRODUCTS ON PRODUCTS.P_ID = INVENTORY.P_ID;